---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8088
      - TORRENTING_PORT=6881
    volumes:
      - ./appdata:/config
      - /mnt/downloads:/downloads
    ports:
      - 8088:8088
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
