services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      #- PUBLIC_KEY=
      #- PUBLIC_KEY_FILE=/home/USER/openssh-server/file
      #- PUBLIC_KEY_DIR=/home/USER/openssh-server/directory/containing/_only_/pubkeys
      #- PUBLIC_KEY_URL=https://github.com/username.keys
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=SENHA
      - USER_PASSWORD_FILE=/home/USUARIO/openssh-server/file
      - USER_NAME=USUARIO
      - LOG_STDOUT=true
    volumes:
      - ./config:/config
    networks:
      macvlan_network:
        ipv4_address: 192.168.1.14
    restart: unless-stopped

networks:
  macvlan_network:
    external: true