---
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - PUBLIC_KEY=
      - PUBLIC_KEY_FILE=/home/USER/openssh-server/file
      - PUBLIC_KEY_DIR=/home/USER/openssh-server/directory/containing/_only_/pubkeys
      - PUBLIC_KEY_URL=https://github.com/username.keys
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=<password>
      - USER_PASSWORD_FILE=/home/USER/openssh-server/file
      - USER_NAME=USER
      - LOG_STDOUT=true
    volumes:
      - ./config:/config
    ports:
      - 59022:2222
    restart: unless-stopped
