---
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - SUBDOMAINS=<domain>
      - TOKEN=<password>
      - UPDATE_IP=ipv4
      - LOG_FILE=true
    volumes:
      - ./config:/config
    restart: unless-stopped
