services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    network_mode: bridge
    dns:
      - 192.168.1.10
    ports:
      - "192.168.1.12:53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'America/Sao_Paulo'
      WEBPASSWORD: 'p4r71cul4'
      DNSMASQ_LISTENING: 'all'
      TEMPERATUREUNIT: 'c'
    volumes:
      - ${HOME}/pihole/etc-pihole:/etc/pihole
      - ${HOME}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
