services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    dns:
      - 192.168.1.10
      - 192.168.1.11
    environment:
      TZ: 'America/Sao_Paulo'
      WEBPASSWORD: 'password'
      DNSMASQ_LISTENING: 'all'
      TEMPERATUREUNIT: 'c'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: "host"